name: 'Send Message'
description: 'Sends message to telegram chat'
inputs:
  successful-message:
    required: true
    
  failure-message:
    required: true

  test-status:
    required: true

  telegram-token:
    required: true

  telegram-chat-id:
    required: true

  telegram-topic-message-id:
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Send message
      run: |
        if [ "$INPUT_TEST_STATUS" == "success" ]; then
          echo $INPUT_SUCCESSFUL_MESSAGE > message.txt
        else
          echo $INPUT_FAILURE_MESSAGE > message.txt
        fi;
        
        echo "Ссылка на последний запуск: $WORKFLOW_RUN_LINK" >> message.txt
        curl -s -X POST "https://api.telegram.org/bot${INPUT_TELEGRAM_TOKEN}/sendMessage" \
        -d "chat_id=${INPUT_TELEGRAM_CHAT_ID}&text=$(cat message.txt)&reply_to_message_id=${INPUT_TELEGRAM_TOPIC_MESSAGE_ID}" > /dev/null 2>&1
      shell: bash
      env:
        INPUT_TEST_STATUS: ${{ inputs.test-status }}
        INPUT_SUCCESSFUL_MESSAGE: ${{ inputs.successful-message }}
        INPUT_FAILURE_MESSAGE: ${{ inputs.failure-message }}
        INPUT_TELEGRAM_TOKEN: ${{ inputs.telegram-token }}
        INPUT_TELEGRAM_CHAT_ID: ${{ inputs.telegram-chat-id }}
        INPUT_TELEGRAM_TOPIC_MESSAGE_ID: ${{ inputs.telegram-topic-message-id }}
        WORKFLOW_RUN_LINK: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
