name: Cache Monitoring on Prod

on:
  schedule:
    - cron: '30 0 * * *'
            
  push:
  #   branches:
  #     - feature/*

jobs:
  validate-cache-headers:
      runs-on: ubuntu-24.04
      timeout-minutes: 10
      steps:
        - uses: actions/checkout@v4
        
        - name: Install Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
            cache: 'npm'
            
        - name: Install dependencies
          run: npm ci
          
        - name: Install Playwright with browsers
          run: npx playwright install --with-deps chromium
          
        - name: Run Playwright test
          id: playwright_test
          run: npx playwright test tests/playwright-tests/cache-checker.spec.ts
          
        - name: Upload results
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: cache-validation-results
            path: |
              results.json
              playwright-report/
              test-logs.txt  # Optional: Include the log file in artifacts for download/archive

        - name: send message
          if: always()
          env:
            STEP_STATUS: ${{ steps.playwright_test.outcome }}
          run: |
            echo $STEP_STATUS
            if [ "$STEP_STATUS" == "success" ]; then
              echo "Cache tests passed" > message.txt
              curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
              -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=$(cat message.txt)&reply_to_message_id=${{ secrets.TELEGRAM_TOPIC_MESSAGE_ID }}" > /dev/null 2>&1
            else

              echo "Cache tests failed" > message.txt
              curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
              -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=$(cat message.txt)&reply_to_message_id=${{ secrets.TELEGRAM_TOPIC_MESSAGE_ID }}" > /dev/null 2>&1
            fi;
        
        # - name: FINAL VALIDATION & SUMMARY TEST REPORT
        #   if: always()
        #   run: |
        #     if [ -f test-logs.txt ]; then
        #       echo "===== Playwright Test Logs ====="
        #       cat test-logs.txt
        #       echo "================================"
        #     else
        #       echo "No test logs found."
        #     fi
