name: Lighthouse Monitoring on Prod

on:
  schedule:
    - cron: '30 0 * * *'
    - cron: '30 8 * * *'
  push:
  #   branches:
  #     - feature/*

env:
  WORKFLOW_RUN_LINK: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

jobs:
  lighthouse:
      runs-on: ubuntu-24.04
      timeout-minutes: 5
      steps:
        - uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Install Lighthouse CI
          run: npm install -g @lhci/cli@0.15.x

        - name: Create Lighthouse directory
          run: mkdir -p .lighthouseci

        - name: Run Lighthouse CI (Desktop) (CLICK HERE TO SEE RESULTS)
          run: |
            lhci autorun --config .lighthouserc.desktop.js --collect.outputPath="./.lighthouseci" || true

            ASSERT_FILE=".lighthouseci/assertion-results.json"

            if [ ! -f "$ASSERT_FILE" ]; then
              echo "❌ Lighthouse CI failed: Desktop (no assertion-results.json)" >> ./lh-errors.txt
              echo "LHCI_FAIL_desktop=1" >> $GITHUB_ENV
            else
              CONTENT=$(cat "$ASSERT_FILE" | tr -d '[:space:]')
              if [ "$CONTENT" != "[]" ]; then
                echo "❌ Lighthouse CI failed: Desktop (assertions failed)" >> ./lh-errors.txt
                echo "LHCI_FAIL_desktop=1" >> $GITHUB_ENV
              fi
            fi

        - name: Run Lighthouse CI (Mobile) (CLICK HERE TO SEE RESULTS)
          run: |
            lhci autorun --config .lighthouserc.mobile.js --collect.outputPath="./.lighthouseci" || true

            ASSERT_FILE=".lighthouseci/assertion-results.json"

            if [ ! -f "$ASSERT_FILE" ]; then
              echo "❌ Lighthouse CI failed: Mobile (no assertion-results.json)" >> ./lh-errors.txt
              echo "LHCI_FAIL_mobile=1" >> $GITHUB_ENV
            else
              CONTENT=$(cat "$ASSERT_FILE" | tr -d '[:space:]')
              if [ "$CONTENT" != "[]" ]; then
                echo "❌ Lighthouse CI failed: Mobile (assertions failed)" >> ./lh-errors.txt
                echo "LHCI_FAIL_mobile=1" >> $GITHUB_ENV
              fi
            fi

        - name: Final validation & summary
          if: always()
          run: |
            echo "===== LIGHTHOUSE TEST SUMMARY ====="
            if [ -f ./lh-errors.txt ]; then
              cat ./lh-errors.txt > message.txt
              cat message.txt
              echo "================================"
              echo ${{ env.WORKFLOW_RUN_LINK }} >> message.txt
              curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
              -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=$(cat message.txt)&reply_to_message_id=${{ secrets.TELEGRAM_TOPIC_MESSAGE_ID }}" > /dev/null 2>&1
              exit 1
            else
              echo "✅ All Lighthouse checks passed." > message.txt
              cat message.txt
              echo ${{ env.WORKFLOW_RUN_LINK }} >> message.txt
              curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
              -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=$(cat message.txt)&reply_to_message_id=${{ secrets.TELEGRAM_TOPIC_MESSAGE_ID }}" > /dev/null 2>&1
            fi
